# Generated by Django 4.0.3 on 2022-04-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='riders',
            new_name='readers',
        ),
    ]
